name: C++ (clang-format)

on:
  push:
    paths:
      - "**/*.cpp"
      - "**/*.hpp"
  pull_request:
    paths:
      - "**/*.cpp"
      - "**/*.hpp"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Install clang-format 18
        uses: aminya/setup-cpp@v1
        with:
          clangformat: 18.1.6
      - name: Run clang-format
        run: clang-format **/*.cpp **/*.hpp -n --Werror
