name: C++ (clang-format)

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Install zsh
        run: sudo apt-get install zsh
      - name: Install clang-format 18
        uses: aminya/setup-cpp@v1
        with:
          clangformat: 18.1.6
      - name: Run clang-format
        run: clang-format-18 **/*.cpp **/*.hpp -n --Werror
        shell: zsh
