name: Python (Ruff)

on:
  push:
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Run ruff check
        uses: chartboost/ruff-action@v1
        with:
          args: check

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Run ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: format --check
